// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPmlrJ81L9rCZISg96uJCkb4_Ao45oH84',
    appId: '1:491434680056:web:your-web-app-id',
    messagingSenderId: '491434680056',
    projectId: 'asl-learning-app-f38b2',
    authDomain: 'asl-learning-app-f38b2.firebaseapp.com',
    storageBucket: 'asl-learning-app-f38b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPmlrJ81L9rCZISg96uJCkb4_Ao45oH84',
    appId: '1:491434680056:android:33828b2604ac2361c8650d',
    messagingSenderId: '491434680056',
    projectId: 'asl-learning-app-f38b2',
    storageBucket: 'asl-learning-app-f38b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPmlrJ81L9rCZISg96uJCkb4_Ao45oH84',
    appId: '1:491434680056:ios:your-ios-app-id',
    messagingSenderId: '491434680056',
    projectId: 'asl-learning-app-f38b2',
    storageBucket: 'asl-learning-app-f38b2.firebasestorage.app',
    iosBundleId: 'com.example.newAsl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPmlrJ81L9rCZISg96uJCkb4_Ao45oH84',
    appId: '1:491434680056:macos:your-macos-app-id',
    messagingSenderId: '491434680056',
    projectId: 'asl-learning-app-f38b2',
    storageBucket: 'asl-learning-app-f38b2.firebasestorage.app',
    iosBundleId: 'com.example.newAsl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPmlrJ81L9rCZISg96uJCkb4_Ao45oH84',
    appId: '1:491434680056:windows:your-windows-app-id',
    messagingSenderId: '491434680056',
    projectId: 'asl-learning-app-f38b2',
    storageBucket: 'asl-learning-app-f38b2.firebasestorage.app',
  );
}
